apiVersion: v1
kind: Pod
metadata:
  name: server
  labels: 
    name: server
spec:
  containers:
  - name: domaci
    image: stefanpejovic/serverdeo:latest
    ports:
    - containerPort: 8081